using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Arkadia.Data;
using Avalonia.Controls;
using Avalonia.Interactivity;

namespace Arkadia;

public partial class CreateVolumeDialog : Window
{
    private readonly List<PlatformRecord>  _platforms;
    private readonly List<DatLineRecord>   _datLines;
    private readonly IReadOnlyList<string> _existingLabels;
    private readonly CatalogService        _catalog;
    private readonly string                _dataDir;

    // Auto-suggest state
    private bool _labelAutoGenerated = true;
    private bool _settingLabel       = false;

    private Dictionary<int, List<DatLineRecord>> _datLinesByPlatformIdx = [];

    public VolumeRecord? Result { get; private set; }

    // Parameterless ctor required by Avalonia XAML compiler
    public CreateVolumeDialog() : this([], [], [], null!, string.Empty) { }

    public CreateVolumeDialog(
        List<PlatformRecord>  platforms,
        List<DatLineRecord>   datLines,
        IReadOnlyList<string> existingLabels,
        CatalogService        catalog,
        string                dataDir)
    {
        InitializeComponent();

        _platforms      = [.. platforms.OrderBy(p => p.Manufacturer, StringComparer.OrdinalIgnoreCase)
                                       .ThenBy(p => p.Name,         StringComparer.OrdinalIgnoreCase)];
        _datLines       = datLines;
        _existingLabels = existingLabels;
        _catalog        = catalog;
        _dataDir        = dataDir;

        PlatformCombo.ItemsSource   = _platforms.Select(PlatformDisplay).ToList();
        PlatformCombo.SelectedIndex = _platforms.Count > 0 ? 0 : -1;

        PlatformCombo.SelectionChanged += OnPlatformChanged;
        RefreshDatLines();
    }

    private static string PlatformDisplay(PlatformRecord p) =>
        p.Manufacturer.Length > 0 ? $"{p.Manufacturer} \u2014 {p.Name}" : p.Name;

    // Called after construction to finish wiring (avoids chicken-and-egg in ctor)
    public void FinishInit()
    {
        _datLinesByPlatformIdx = [];
        for (int i = 0; i < _platforms.Count; i++)
        {
            var pid  = _platforms[i].Id;
            var list = _datLines.Where(d => d.PlatformId == pid).ToList();
            _datLinesByPlatformIdx[i] = list;
        }
        RefreshDatLines();
    }

    // ── Platform / DAT line selection ─────────────────────────────────────────

    private void OnPlatformChanged(object? sender, SelectionChangedEventArgs e)
    {
        RefreshDatLines();
        Validate();
    }

    private void RefreshDatLines()
    {
        var idx      = PlatformCombo.SelectedIndex;
        var filtered = _datLinesByPlatformIdx.TryGetValue(idx, out var dl) ? dl : [];
        DatLineCombo.ItemsSource   = filtered.Select(d => d.Name).ToList();
        DatLineCombo.SelectedIndex = filtered.Count > 0 ? 0 : -1;
        Validate();
    }

    private void OnDatLineChanged(object? sender, SelectionChangedEventArgs e)
    {
        if (_labelAutoGenerated)
            UpdateSuggestedLabel();
        Validate();
    }

    // ── Label auto-suggest ────────────────────────────────────────────────────

    private void OnLabelChanged(object? sender, TextChangedEventArgs e)
    {
        if (!_settingLabel)
            _labelAutoGenerated = false;
        Validate();
    }

    private void UpdateSuggestedLabel()
    {
        var datLine = GetCurrentDatLine();
        if (datLine is null) return;

        _settingLabel   = true;
        LabelInput.Text = BuildSuggestedLabel(datLine);
        _settingLabel   = false;
    }

    private string BuildSuggestedLabel(DatLineRecord datLine)
    {
        var n = NextNumber(datLine.Id);
        return $"{datLine.Id}-{n:D3}";
    }

    private int NextNumber(string prefix)
    {
        var pattern = prefix + "-";
        int max     = 0;
        foreach (var label in _existingLabels)
        {
            if (!label.StartsWith(pattern, StringComparison.OrdinalIgnoreCase)) continue;
            var tail = label[pattern.Length..];
            if (int.TryParse(tail, out var n) && n > max)
                max = n;
        }
        return max + 1;
    }

    // ── Size suggestion ───────────────────────────────────────────────────────

    private void OnSuggestSize(object? sender, RoutedEventArgs e)
    {
        var datLine = GetCurrentDatLine();
        if (datLine is null || datLine.DataStorePath.Length == 0) return;

        var dbPath = Path.Combine(_dataDir, datLine.DataStorePath);
        if (!File.Exists(dbPath)) return;

        var assignedIds    = _catalog.GetAssignedDerivedIdsByDatLine(datLine.Id);
        var (_, unassigned) = new DatLineStore(dbPath).GetUnassignedPresentStats(assignedIds);

        var suggestedBytes = (long)(unassigned * 1.10);
        var suggestedGb    = suggestedBytes / (1024.0 * 1024 * 1024);
        PlannedSizeInput.Text = suggestedGb.ToString("F2", System.Globalization.CultureInfo.InvariantCulture);
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private DatLineRecord? GetCurrentDatLine()
    {
        var platIdx = PlatformCombo.SelectedIndex;
        var dlIdx   = DatLineCombo.SelectedIndex;
        if (!_datLinesByPlatformIdx.TryGetValue(platIdx, out var dls)) return null;
        return dlIdx >= 0 && dlIdx < dls.Count ? dls[dlIdx] : null;
    }

    // ── Validation ────────────────────────────────────────────────────────────

    private void Validate()
    {
        var label    = LabelInput.Text?.Trim()       ?? "";
        var sizeText = PlannedSizeInput.Text?.Trim() ?? "";
        bool sizeOk  = double.TryParse(sizeText, System.Globalization.NumberStyles.Any,
                           System.Globalization.CultureInfo.InvariantCulture, out var size) && size > 0;
        bool datOk   = DatLineCombo.SelectedIndex >= 0;

        string? err = sizeText.Length > 0 && !sizeOk ? "Planned size must be a positive number." : null;

        ErrorText.Text      = err ?? "";
        ErrorText.IsVisible = err is not null;
        ConfirmButton.IsEnabled = label.Length > 0 && sizeOk && datOk && err is null;
    }

    private void OnFieldChanged(object? sender, TextChangedEventArgs e)     => Validate();
    private void OnFieldChanged(object? sender, SelectionChangedEventArgs e) => Validate();

    // ── Confirm / Cancel ──────────────────────────────────────────────────────

    private void OnConfirm(object? sender, RoutedEventArgs e)
    {
        var sizeGb  = double.Parse(PlannedSizeInput.Text!.Trim(),
                          System.Globalization.CultureInfo.InvariantCulture);
        var datLine = GetCurrentDatLine();
        if (datLine is null) return;

        Result = new VolumeRecord
        {
            Id               = Guid.NewGuid().ToString("N"),
            Label            = LabelInput.Text!.Trim(),
            PlatformId       = datLine.PlatformId,
            DatLineId        = datLine.Id,
            Status           = "init",
            PlannedSizeBytes = (long)(sizeGb * 1024 * 1024 * 1024),
            ActualSizeBytes  = 0,
            CreatedAt        = DateTime.UtcNow,
        };
        Close(true);
    }

    private void OnCancel(object? sender, RoutedEventArgs e) => Close(false);
}
