using System;
using System.IO;
using System.Threading;
using Arkadia.Data;
using Arkadia.Providers;
using Avalonia.Controls;
using Avalonia.Interactivity;
using Avalonia.Media;
using Avalonia.Platform.Storage;

namespace Arkadia;

public partial class ScreenScraperCacheBuilderDialog : Window
{
    private readonly CatalogService _catalog;
    private CancellationTokenSource? _cts;
    private bool _outputZipIsAutoGenerated = true;

    public ScreenScraperCacheBuilderDialog() : this(null!) { }

    public ScreenScraperCacheBuilderDialog(CatalogService catalog)
    {
        InitializeComponent();
        _catalog = catalog;

        StagingRootField.Text          = Path.Combine(AppContext.BaseDirectory, ArkadiaFolders.StagingCache);
        MaxScrapesField.Text           = "19000";
        KeepStagingCheck.IsChecked     = true;
        IndexAfterBuildCheck.IsChecked = true;

        PackageNameField.TextChanged += OnPackageNameChanged;
    }

    // ── Browse handlers ───────────────────────────────────────────────────────

    private async void OnBrowseCsv(object? sender, RoutedEventArgs e)
    {
        var incomingCsvPath = Path.Combine(AppContext.BaseDirectory, ArkadiaFolders.IncomingCsv);
        IStorageFolder? startFolder = null;
        if (Directory.Exists(incomingCsvPath))
            startFolder = await StorageProvider.TryGetFolderFromPathAsync(incomingCsvPath);

        var files = await StorageProvider.OpenFilePickerAsync(new FilePickerOpenOptions
        {
            Title                  = "Select ScreenScraper Gamelist CSV",
            AllowMultiple          = false,
            SuggestedStartLocation = startFolder,
            FileTypeFilter =
            [
                new FilePickerFileType("CSV File") { Patterns = ["*.csv"] },
                new FilePickerFileType("All Files") { Patterns = ["*.*"] },
            ],
        });
        if (files.Count == 0) return;
        if (files[0].TryGetLocalPath() is not string path) return;

        CsvPathField.Text = path;

        // Auto-fill package name from CSV filename stem if package name is still empty
        if (string.IsNullOrWhiteSpace(PackageNameField.Text))
            PackageNameField.Text = CacheBuilderHelper.SanitizePackageName(
                Path.GetFileNameWithoutExtension(path));
    }

    private async void OnBrowseOutputZip(object? sender, RoutedEventArgs e)
    {
        var file = await StorageProvider.SaveFilePickerAsync(new FilePickerSaveOptions
        {
            Title            = "Save Cache Package ZIP As",
            DefaultExtension = "zip",
            FileTypeChoices  =
            [
                new FilePickerFileType("ZIP Archive") { Patterns = ["*.zip"] },
            ],
        });
        if (file?.TryGetLocalPath() is string path)
        {
            OutputZipPathField.Text    = path;
            _outputZipIsAutoGenerated  = false;
        }
    }

    private async void OnBrowseStagingRoot(object? sender, RoutedEventArgs e)
    {
        var folders = await StorageProvider.OpenFolderPickerAsync(new FolderPickerOpenOptions
        {
            Title = "Select Staging Root Folder",
        });
        if (folders.Count > 0 && folders[0].TryGetLocalPath() is string path)
            StagingRootField.Text = path;
    }

    private void OnPackageNameChanged(object? sender, Avalonia.Controls.TextChangedEventArgs e)
    {
        if (!_outputZipIsAutoGenerated) return;
        var name = CacheBuilderHelper.SanitizePackageName(PackageNameField.Text?.Trim() ?? "");
        OutputZipPathField.Text = name.Length > 0
            ? ToAbsolute(CacheBuilderHelper.DefaultOutputZipPath(name))
            : "";
    }

    // ── Build ─────────────────────────────────────────────────────────────────

    private async void OnBuildPackage(object? sender, RoutedEventArgs e)
    {
        ValidationMsg.IsVisible = false;

        var packageName = CacheBuilderHelper.SanitizePackageName(PackageNameField.Text?.Trim() ?? "");
        var stagingRoot = ToAbsolute(StagingRootField.Text?.Trim() ?? "");
        var outputZip   = ResolveOutputZip(OutputZipPathField.Text?.Trim(), packageName);
        var csvPath     = CsvPathField.Text?.Trim() ?? "";
        var systemId    = SystemIdField.Text?.Trim() ?? "";
        var systemName  = SystemNameField.Text?.Trim() ?? "";
        var maxScrapes  = int.TryParse(MaxScrapesField.Text?.Trim(), out var ms) ? ms : 0;

        var u        = _catalog.GetSetting("screenscraper_username");
        var pw       = _catalog.GetSetting("screenscraper_password");
        var di       = _catalog.GetSetting("screenscraper_dev_id");
        var dp       = _catalog.GetSetting("screenscraper_dev_password");
        var softName = _catalog.GetSetting("screenscraper_softname").Trim();

        var err = CacheBuilderHelper.Validate(
            csvPath, systemId, systemName, packageName, outputZip, stagingRoot,
            maxScrapes, credentialsConfigured: ScraperProviderInfo.IsScreenScraperConfigured(u, pw, di, dp),
            softname: softName);
        if (err is not null)
        {
            ValidationMsg.Text      = err;
            ValidationMsg.IsVisible = true;
            return;
        }

        // Ensure output and staging directories exist before the builder starts
        var outDir = Path.GetDirectoryName(outputZip);
        if (!string.IsNullOrEmpty(outDir))
            Directory.CreateDirectory(outDir);
        Directory.CreateDirectory(stagingRoot);

        SetBuilding(true);
        SetStatus("Starting build...");
        _cts = new CancellationTokenSource();

        var opts = new ScreenScraperCachePackageBuildOptions(
            CsvPath:          csvPath,
            SystemId:         systemId,
            SystemName:       systemName,
            PackageName:      packageName,
            OutputZipPath:    outputZip,
            StagingRoot:      stagingRoot,
            DevId:            di,
            DevPassword:      dp,
            Username:         u,
            Password:         pw,
            MaxScrapesThisRun: maxScrapes,
            Force:            ForceRebuildCheck.IsChecked    == true,
            UpdatePayloads:   UpdatePayloadsCheck.IsChecked  == true,
            IndexAfterBuild:  IndexAfterBuildCheck.IsChecked == true,
            KeepStaging:      KeepStagingCheck.IsChecked     == true);

        var fetcher  = new ScreenScraperDetailsFetcher(di, dp, u, pw, systemId, softName);
        var mediaDownloader = new ScreenScraperMediaDownloader();
        var builder         = new ScreenScraperCachePackageBuilder(fetcher, mediaDownloader, _catalog);
        var progress        = new System.Progress<string>(msg => SetStatus(msg));

        ScreenScraperCachePackageBuildResult? result = null;
        try
        {
            result = await builder.BuildAsync(opts, progress, _cts.Token);
        }
        catch (OperationCanceledException)
        {
            SetStatus("Build cancelled.");
        }
        catch (Exception ex)
        {
            SetStatus($"Error: {ex.Message}", isError: true);
        }
        finally
        {
            _cts?.Dispose();
            _cts = null;
            SetBuilding(false);
        }

        if (result is null) return;

        SetStatus(CacheBuilderHelper.GetResultStatus(result),
                  isError: !result.IsComplete && !result.WasAlreadyBuilt
                           && !result.HitSafeLimit && !result.HitRateLimit);

        if (result.HitSafeLimit)
        {
            await new InfoDialog(
                "ScreenScraper safe daily limit reached",
                "Arkadia has reached the configured safe ScreenScraper scrape limit for this run.\n\n" +
                "The cache build has been stopped automatically.\n" +
                "No partial ZIP was created.\n" +
                "Staging data was preserved and the build can be resumed later.")
                .ShowDialog(this);
        }
        else if (result.HitRateLimit)
        {
            await new InfoDialog(
                "ScreenScraper rate limit reached",
                "ScreenScraper reported a rate limit. The cache build has been stopped.\n\n" +
                "No partial ZIP was created.\n" +
                "Staging data was preserved and the build can be resumed later.")
                .ShowDialog(this);
        }
    }

    private void OnCancelBuild(object? sender, RoutedEventArgs e) => _cts?.Cancel();

    private void OnClose(object? sender, RoutedEventArgs e) => Close();

    // ── UI state helpers ──────────────────────────────────────────────────────

    private void SetBuilding(bool building)
    {
        BuildBtn.IsEnabled       = !building;
        CancelBuildBtn.IsVisible = building;
        CloseBtn.IsVisible       = !building;
        BuildProgress.IsVisible  = building;
        StatusPanel.IsVisible    = true;
    }

    private void SetStatus(string message, bool isError = false)
    {
        StatusPanel.IsVisible = true;
        StatusText.Text       = message;
        StatusText.Foreground = isError
            ? new SolidColorBrush(Color.Parse("#EF5350"))
            : new SolidColorBrush(Color.Parse("#888899"));
    }

    // ── Path helpers ──────────────────────────────────────────────────────────

    private static string ToAbsolute(string path)
        => Path.IsPathRooted(path) ? path : Path.Combine(AppContext.BaseDirectory, path);

    private static string ResolveOutputZip(string? raw, string packageName)
    {
        if (string.IsNullOrWhiteSpace(raw))
            return ToAbsolute(CacheBuilderHelper.DefaultOutputZipPath(packageName));
        return ToAbsolute(raw);
    }

    // ── Close guard ───────────────────────────────────────────────────────────

    protected override void OnClosing(WindowClosingEventArgs e)
    {
        if (_cts is not null)
            e.Cancel = true; // block window close while build is running
        base.OnClosing(e);
    }
}
